export const VIETNAMESE_CITIES = [
  { value: null, label: 'Tất cả tỉnh thành' },
  { value: 'Thành phố Hà Nội', label: 'Hà Nội' },
  { value: 'Thành phố Hồ Chí Minh', label: 'Hồ Chí Minh' },
  { value: 'Thành phố Hải Phòng', label: 'Hải Phòng' },
  { value: 'Thành phố Đà Nẵng', label: 'Đà Nẵng' },
  { value: 'Thành phố Cần Thơ', label: 'Cần Thơ' },
  { value: 'Tỉnh An Giang', label: 'An Giang' },
  { value: 'Tỉnh Bà Rịa - Vũng Tàu', label: 'Bà Rịa - Vũng Tàu' },
  { value: 'Tỉnh Bắc Giang', label: 'Bắc Giang' },
  { value: 'Tỉnh Bắc Kạn', label: 'Bắc Kạn' },
  { value: 'Tỉnh Bạc Liêu', label: 'Bạc Liêu' },
  { value: 'Tỉnh Bắc Ninh', label: 'Bắc Ninh' },
  { value: 'Tỉnh Bến Tre', label: 'Bến Tre' },
  { value: 'Tỉnh Bình Định', label: 'Bình Định' },
  { value: 'Tỉnh Bình Dương', label: 'Bình Dương' },
  { value: 'Tỉnh Bình Phước', label: 'Bình Phước' },
  { value: 'Tỉnh Bình Thuận', label: 'Bình Thuận' },
  { value: 'Tỉnh Cà Mau', label: 'Cà Mau' },
  { value: 'Tỉnh Cao Bằng', label: 'Cao Bằng' },
  { value: 'Tỉnh Đắk Lắk', label: 'Đắk Lắk' },
  { value: 'Tỉnh Đắk Nông', label: 'Đắk Nông' },
  { value: 'Tỉnh Điện Biên', label: 'Điện Biên' },
  { value: 'Tỉnh Đồng Nai', label: 'Đồng Nai' },
  { value: 'Tỉnh Đồng Tháp', label: 'Đồng Tháp' },
  { value: 'Tỉnh Gia Lai', label: 'Gia Lai' },
  { value: 'Tỉnh Hà Giang', label: 'Hà Giang' },
  { value: 'Tỉnh Hà Nam', label: 'Hà Nam' },
  { value: 'Tỉnh Hà Tĩnh', label: 'Hà Tĩnh' },
  { value: 'Tỉnh Hải Dương', label: 'Hải Dương' },
  { value: 'Tỉnh Hậu Giang', label: 'Hậu Giang' },
  { value: 'Tỉnh Hòa Bình', label: 'Hòa Bình' },
  { value: 'Tỉnh Hưng Yên', label: 'Hưng Yên' },
  { value: 'Tỉnh Khánh Hòa', label: 'Khánh Hòa' },
  { value: 'Tỉnh Kiên Giang', label: 'Kiên Giang' },
  { value: 'Tỉnh Kon Tum', label: 'Kon Tum' },
  { value: 'Tỉnh Lai Châu', label: 'Lai Châu' },
  { value: 'Tỉnh Lâm Đồng', label: 'Lâm Đồng' },
  { value: 'Tỉnh Lạng Sơn', label: 'Lạng Sơn' },
  { value: 'Tỉnh Lào Cai', label: 'Lào Cai' },
  { value: 'Tỉnh Long An', label: 'Long An' },
  { value: 'Tỉnh Nam Định', label: 'Nam Định' },
  { value: 'Tỉnh Nghệ An', label: 'Nghệ An' },
  { value: 'Tỉnh Ninh Bình', label: 'Ninh Bình' },
  { value: 'Tỉnh Ninh Thuận', label: 'Ninh Thuận' },
  { value: 'Tỉnh Phú Thọ', label: 'Phú Thọ' },
  { value: 'Tỉnh Phú Yên', label: 'Phú Yên' },
  { value: 'Tỉnh Quảng Bình', label: 'Quảng Bình' },
  { value: 'Tỉnh Quảng Nam', label: 'Quảng Nam' },
  { value: 'Tỉnh Quảng Ngãi', label: 'Quảng Ngãi' },
  { value: 'Tỉnh Quảng Ninh', label: 'Quảng Ninh' },
  { value: 'Tỉnh Quảng Trị', label: 'Quảng Trị' },
  { value: 'Tỉnh Sóc Trăng', label: 'Sóc Trăng' },
  { value: 'Tỉnh Sơn La', label: 'Sơn La' },
  { value: 'Tỉnh Tây Ninh', label: 'Tây Ninh' },
  { value: 'Tỉnh Thái Bình', label: 'Thái Bình' },
  { value: 'Tỉnh Thái Nguyên', label: 'Thái Nguyên' },
  { value: 'Tỉnh Thanh Hóa', label: 'Thanh Hóa' },
  { value: 'Tỉnh Thừa Thiên Huế', label: 'Thừa Thiên Huế' },
  { value: 'Tỉnh Tiền Giang', label: 'Tiền Giang' },
  { value: 'Tỉnh Trà Vinh', label: 'Trà Vinh' },
  { value: 'Tỉnh Tuyên Quang', label: 'Tuyên Quang' },
  { value: 'Tỉnh Vĩnh Long', label: 'Vĩnh Long' },
  { value: 'Tỉnh Vĩnh Phúc', label: 'Vĩnh Phúc' },
  { value: 'Tỉnh Yên Bái', label: 'Yên Bái' }
]
